controller: 
    enableCustomResources: true
    enableSnippets: true
    volumes:
      - name: extra-conf
        configMap:
          name: nginx-configs
    volumeMounts:
      - name: extra-conf
        mountPath: /etc/nginx/extra-conf/
    config: 
      name: "nginx-ingress-config"
      entries: 
        client-max-body-size: 100m
        proxy-connect-timeout: 75s
        proxy-read-timeout: 600s
        proxy_next_upstream: "error timeout non_idempotent http_503 http_504"
        proxy_next_upstream_timeout: "10s"
        proxy-next-upstream-tries: "10"
        worker-rlimit-nofile: "65536"
        worker-connections: "8192"
        keepalive: "32"
        max-fails: "0" 
        fail-timeout: "5s"
        main-snippets: |
          load_module modules/ngx_http_js_module.so;
          load_module modules/ngx_http_cookie_flag_filter_module.so;
